window.FCW_QUOTES = [
  { q: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", a: "Aristotle", c: "Discipline" },
  { q: "It does not matter how slowly you go as long as you do not stop.", a: "Confucius", c: "Discipline" },
  { q: "Success is the sum of small efforts, repeated day in and day out.", a: "Robert Collier", c: "Discipline" },
  { q: "The secret of getting ahead is getting started.", a: "Mark Twain", c: "Discipline" },
  { q: "Motivation is what gets you started. Habit is what keeps you going.", a: "Jim Ryun", c: "Discipline" },
  { q: "Great things are done by a series of small things brought together.", a: "Vincent van Gogh", c: "Discipline" },
  { q: "Discipline is the bridge between goals and accomplishment.", a: "Jim Rohn", c: "Discipline" },
  { q: "Either you run the day, or the day runs you.", a: "Jim Rohn", c: "Discipline" },
  { q: "Success isn't overnight. It's when every day you get a little better than the day before.", a: "Dwayne Johnson", c: "Discipline" },
  { q: "The successful warrior is the average man, with laser-like focus.", a: "Bruce Lee", c: "Discipline" },
  { q: "There is no substitute for hard work.", a: "Thomas Edison", c: "Hard Work" },
  { q: "Genius is one percent inspiration and ninety-nine percent perspiration.", a: "Thomas Edison", c: "Hard Work" },
  { q: "Opportunity is missed by most people because it is dressed in overalls and looks like work.", a: "Thomas Edison", c: "Hard Work" },
  { q: "The only place where success comes before work is in the dictionary.", a: "Vidal Sassoon", c: "Hard Work" },
  { q: "Don't wish it were easier. Wish you were better.", a: "Jim Rohn", c: "Hard Work" },
  { q: "You don't have to be great to start, but you have to start to be great.", a: "Zig Ziglar", c: "Hard Work" },
  { q: "What you do today can improve all your tomorrows.", a: "Ralph Marston", c: "Hard Work" },
  { q: "Do what you can, with what you have, where you are.", a: "Theodore Roosevelt", c: "Hard Work" },
  { q: "The future depends on what you do today.", a: "Mahatma Gandhi", c: "Hard Work" },
  { q: "The only way to do great work is to love what you do.", a: "Steve Jobs", c: "Hard Work" },
  { q: "Success is walking from failure to failure with no loss of enthusiasm.", a: "Winston Churchill", c: "Success" },
  { q: "Success usually comes to those who are too busy to be looking for it.", a: "Henry David Thoreau", c: "Success" },
  { q: "Success is not final, failure is not fatal: it is the courage to continue that counts.", a: "Winston Churchill", c: "Success" },
  { q: "Try not to become a man of success. Rather become a man of value.", a: "Albert Einstein", c: "Success" },
  { q: "The way to get started is to quit talking and begin doing.", a: "Walt Disney", c: "Success" },
  { q: "Success is liking yourself, liking what you do, and liking how you do it.", a: "Maya Angelou", c: "Success" },
  { q: "Success is how high you bounce when you hit bottom.", a: "George S. Patton", c: "Success" },
  { q: "Don't count the days, make the days count.", a: "Muhammad Ali", c: "Success" },
  { q: "The road to success and the road to failure are almost exactly the same.", a: "Colin R. Davis", c: "Success" },
  { q: "Success is not in never failing, but in rising every time you fall.", a: "Oliver Goldsmith", c: "Success" },
  { q: "I have not failed. I've just found 10,000 ways that won't work.", a: "Thomas Edison", c: "Resilience" },
  { q: "Our greatest glory is not in never falling, but in rising every time we fall.", a: "Confucius", c: "Resilience" },
  { q: "Failure is simply the opportunity to begin again, this time more intelligently.", a: "Henry Ford", c: "Resilience" },
  { q: "A winner is just a loser who tried one more time.", a: "George M. Moore", c: "Resilience" },
  { q: "Fall seven times, stand up eight.", a: "Japanese Proverb", c: "Resilience" },
  { q: "You may have to fight a battle more than once to win it.", a: "Margaret Thatcher", c: "Resilience" },
  { q: "Our greatest weakness lies in giving up.", a: "Thomas Edison", c: "Resilience" },
  { q: "Failure is the condiment that gives success its flavor.", a: "Truman Capote", c: "Resilience" },
  { q: "Mistakes are the portals of discovery.", a: "James Joyce", c: "Resilience" },
  { q: "The master has failed more times than the beginner has even tried.", a: "Stephen McCranie", c: "Resilience" },
  { q: "It is during our darkest moments that we must focus to see the light.", a: "Aristotle", c: "Focus" },
  { q: "Concentrate all your thoughts upon the work at hand.", a: "Alexander Graham Bell", c: "Focus" },
  { q: "You will never reach your destination if you stop and throw stones at every dog that barks.", a: "Winston Churchill", c: "Focus" },
  { q: "The successful person makes a habit of doing what the failing person doesn't like to do.", a: "Thomas Edison", c: "Focus" },
  { q: "Starve your distractions, feed your focus.", a: "Unknown", c: "Focus" },
  { q: "Focus on being productive instead of busy.", a: "Tim Ferriss", c: "Focus" },
  { q: "You can't depend on your eyes when your imagination is out of focus.", a: "Mark Twain", c: "Focus" },
  { q: "Where focus goes, energy flows.", a: "Tony Robbins", c: "Focus" },
  { q: "Lack of direction, not lack of time, is the problem.", a: "Zig Ziglar", c: "Focus" },
  { q: "The key is not to prioritize what's on your schedule, but to schedule your priorities.", a: "Stephen Covey", c: "Focus" },
  { q: "Live as if you were to die tomorrow. Learn as if you were to live forever.", a: "Mahatma Gandhi", c: "Learning" },
  { q: "An investment in knowledge pays the best interest.", a: "Benjamin Franklin", c: "Learning" },
  { q: "The beautiful thing about learning is that nobody can take it away from you.", a: "B.B. King", c: "Learning" },
  { q: "Education is the most powerful weapon which you can use to change the world.", a: "Nelson Mandela", c: "Learning" },
  { q: "The only person who is educated is the one who has learned how to learn and change.", a: "Carl Rogers", c: "Learning" },
  { q: "Anyone who stops learning is old, whether at twenty or eighty.", a: "Henry Ford", c: "Learning" },
  { q: "I am still learning.", a: "Michelangelo", c: "Learning" },
  { q: "The more I learn, the more I realize how much I don't know.", a: "Albert Einstein", c: "Learning" },
  { q: "Learning never exhausts the mind.", a: "Leonardo da Vinci", c: "Learning" },
  { q: "Knowledge speaks, but wisdom listens.", a: "Jimi Hendrix", c: "Learning" },
  { q: "Courage is resistance to fear, mastery of fear, not absence of fear.", a: "Mark Twain", c: "Courage" },
  { q: "Do one thing every day that scares you.", a: "Eleanor Roosevelt", c: "Courage" },
  { q: "Everything you've ever wanted is on the other side of fear.", a: "George Addair", c: "Courage" },
  { q: "He who is not courageous enough to take risks will accomplish nothing in life.", a: "Muhammad Ali", c: "Courage" },
  { q: "Courage doesn't always roar.", a: "Mary Anne Radmacher", c: "Courage" },
  { q: "The only way out is through.", a: "Robert Frost", c: "Courage" },
  { q: "Feel the fear and do it anyway.", a: "Susan Jeffers", c: "Courage" },
  { q: "You gain strength, courage, and confidence by every experience in which you really stop to look fear in the face.", a: "Eleanor Roosevelt", c: "Courage" },
  { q: "It takes courage to grow up and become who you really are.", a: "E.E. Cummings", c: "Courage" },
  { q: "Fortune favors the bold.", a: "Latin Proverb", c: "Courage" },
  { q: "The future belongs to those who believe in the beauty of their dreams.", a: "Eleanor Roosevelt", c: "Dreams" },
  { q: "If you can dream it, you can do it.", a: "Walt Disney", c: "Dreams" },
  { q: "All our dreams can come true, if we have the courage to pursue them.", a: "Walt Disney", c: "Dreams" },
  { q: "A goal without a plan is just a wish.", a: "Antoine de Saint-Exupery", c: "Dreams" },
  { q: "Setting goals is the first step in turning the invisible into the visible.", a: "Tony Robbins", c: "Dreams" },
  { q: "Go confidently in the direction of your dreams! Live the life you've imagined.", a: "Henry David Thoreau", c: "Dreams" },
  { q: "Whatever you are, be a good one.", a: "Abraham Lincoln", c: "Dreams" },
  { q: "If opportunity doesn't knock, build a door.", a: "Milton Berle", c: "Dreams" },
  { q: "A person who never made a mistake never tried anything new.", a: "Albert Einstein", c: "Dreams" },
  { q: "Your limitation, it's only your imagination.", a: "Unknown", c: "Dreams" },
  { q: "Rivers know this: there is no hurry. We shall get there someday.", a: "A.A. Milne", c: "Patience" },
  { q: "Adopt the pace of nature: her secret is patience.", a: "Ralph Waldo Emerson", c: "Patience" },
  { q: "Patience is bitter, but its fruit is sweet.", a: "Aristotle", c: "Patience" },
  { q: "Great things take time.", a: "Unknown", c: "Patience" },
  { q: "A little progress each day adds up to big results.", a: "Unknown", c: "Patience" },
  { q: "The secret of patience is to do something else in the meantime.", a: "Croft M. Pentz", c: "Patience" },
  { q: "Slow and steady wins the race.", a: "Aesop", c: "Patience" },
  { q: "The journey of a thousand miles begins with one step.", a: "Lao Tzu", c: "Patience" },
  { q: "No great thing is created suddenly.", a: "Epictetus", c: "Patience" },
  { q: "It is not the mountain we conquer, but ourselves.", a: "Edmund Hillary", c: "Patience" },
  { q: "Whether you think you can, or you think you can't, you're right.", a: "Henry Ford", c: "Mindset" },
  { q: "The mind is everything. What you think you become.", a: "Buddha", c: "Mindset" },
  { q: "He who conquers himself is the mightiest warrior.", a: "Confucius", c: "Mindset" },
  { q: "We become what we think about most of the time.", a: "Earl Nightingale", c: "Mindset" },
  { q: "Knowing yourself is the beginning of all wisdom.", a: "Aristotle", c: "Mindset" },
  { q: "You are never too old to set another goal or to dream a new dream.", a: "C.S. Lewis", c: "Mindset" },
  { q: "The greatest wealth is health.", a: "Virgil", c: "Mindset" },
  { q: "Be yourself; everyone else is already taken.", a: "Oscar Wilde", c: "Mindset" },
  { q: "What we fear doing most is usually what we most need to do.", a: "Ralph Waldo Emerson", c: "Mindset" },
  { q: "Act as if what you do makes a difference. It does.", a: "William James", c: "Mindset" }
];